### PR TITLE
Url zoom, A fix for issue #1108 

### PR DESCRIPTION
**Pull request by voscarmv**
## Description

A fix for issue #1108:

For URLs with an object id such as rapideditor.org/rapid#id=w1204555438 users must pres Z to zoom into the object with id w1204555438

This fix zooms to the object automatically once the map is loaded.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [✅] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

https://github.com/facebook/Rapid/issues/1108

## Mobile & Desktop Screenshots/Recordings

image

## Added tests?

- [ ] 👍 yes
- [✅] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [✅] 🙅 no documentation needed

### CODE REVIEW

**Comment by voscarmv** [comment]
Builds fail but it works well on my local environment

**Comment by Bonkles** [comment]
Ah super quick @voscarmv you will need to run the code linter locally- `npm run lint`. I didn't cover this- my fault! 

If you click into the test failures above, you will see that the linter is unhappy about some of your code formatting. Try to resolve the issues and update the PR branch once you're satisfied. 

Incidentally, VSCode should give you a hint in the 'Problems' pane of the console, any errors will be called out there pretty clearly. 

Try it for yourself- take any string and change it from double to singlequote- you should see something like: 

image

**Comment by voscarmv** [comment]
> Ah super quick @voscarmv you will need to run the code linter locally- `npm run lint`. I didn't cover this- my fault!
> 
> If you click into the test failures above, you will see that the linter is unhappy about some of your code formatting. Try to resolve the issues and update the PR branch once you're satisfied.
> 
> Incidentally, VSCode should give you a hint in the 'Problems' pane of the console, any errors will be called out there pretty clearly.
> 
> Try it for yourself- take any string and change it from double to singlequote- you should see something like:
> 
> image

Got it @Bonkles !

**Comment by voscarmv** [comment]
@Bonkles I made a clean fork and a new PR with all linter issues fixed if you want to check it out: #1173

**Comment by bhousel** [comment]
moved to #1173

**Pull request closed without merging**
