### PR TITLE
Add markdown styling to README.md

### PR DESCRIPTION
**Pull request by lauble**
## Description
Referencing Issue #1177

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [x] 📜 README.md
- [ ] 📓 docs
- [ ] 📕 storybook
- [ ] 🙅 no documentation  #needed

### CODE REVIEW

**Comment by lauble** [comment]
Screenshot of how the table gets displayed in GitHub

Screenshot 2023-10-27 at 10 36 22 AM

**Comment by lauble** [comment]
Updated emojis

Screenshot 2023-10-30 at 4 00 26 PM

**Comment by lauble** [comment]
@Bonkles Do you know why I might be getting build errors? The only changes I made were to the README file.

**Comment by Bonkles** [comment]
No idea what's up there- looks like some sort of server error that's probably transient!

**Comment by bhousel** [comment]
Thanks @lauble , this PR includes a whole lot of extra stuff in it, so I'm just going to `git cherry-pick` your last few commits.
- 9296eb4
- 56f2854
- e857e01

**Comment by bhousel** [comment]
merged as
09fbc2646 2023-11-08 align Rapid h1 to center <Lauren>
5b25e31ae 2023-11-08 update request emojis <Lauren>
09cdca37d 2023-11-08 create table for request instructions <Lauren>

**Comment by lauble** [comment]
Thanks @bhousel!

**Comment by lauble** [comment]
> Thanks @lauble , this PR includes a whole lot of extra stuff in it, so I'm just going to `git cherry-pick` your last few commits.
> 
> * [9296eb4](https://github.com/facebook/Rapid/commit/9296eb4df64d6aecf9fc1b5233e9713853a285d5)
> * [56f2854](https://github.com/facebook/Rapid/commit/56f2854fed758a102c5df4b484a36ad3b24c5bb4)
> * [e857e01](https://github.com/facebook/Rapid/commit/e857e0115051b444e91938d872f3af159cd4f137)

Apologies for the extra stuff, I'm working with @Bonkles today to get that sorted out.

**Comment by bhousel** [comment]
No worries 👍 
It looks like you continued this `readme-style` branch off that other working branch .

You can always take a fresh working branch off of `main` and cherry-pick commits from any of your other branches onto it:

```sh
git checkout main
git pull origin
git checkout -b fresh_branch
git cherry-pick  <commit sha>
```

This will help make it so that the work on `fresh_branch` merges back to `main` cleanly.

**Comment by lauble** [comment]
That is precisely what I did 😆 . Thank you for the info on cherry picking commits! That will definitely come in handy in the future.

**Pull request closed without merging**
