### PR TITLE
Wayback followup fixes

### LINKED ISSUE #1377: Tooltip cut of for wayback imagery
### Description

image

The tooltips for the items below do work, so I assume this one is attached to the text and  not to the wrapping UI outline?

### Screenshots

_No response_

### Version

canary

### What browser are you seeing the problem on? What version are you running?

_No response_

### The OS you're using

_No response_

### Steps to reproduce

https://rapideditor.org/canary#map=17.85/52.70497/13.88678&background=Brandenburg-DOP20c&datasets=fbRoads,msBuildings&disable_features=boundaries => hover UI element

### The browser URL at the time you encountered the bug

.

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

_No response_

### LINKED ISSUE #1379: Wayback imagery: Unclear interaction between image layer and feature
### Description

Video (at the end):

https://github.com/facebook/Rapid/assets/111561/d2613fdb-e347-435f-9399-036841b45a6d

1. I activate the wayback images => the regular image layers get deselected, which is great
2. I activate a regular image layer again => the wayback images checkbox is still seletected
3. ==> the only way to re-pick the wayback images is to unselect and reselect those. I think the checkbox needs to unselect once I switch back to a regular image layer

### Screenshots

_No response_

### Version

canary

### What browser are you seeing the problem on? What version are you running?

_No response_

### The OS you're using

_No response_

### Steps to reproduce

.

### The browser URL at the time you encountered the bug

https://rapideditor.org/canary#map=17.85/52.70497/13.88678&background=EsriWorldImagery&datasets=fbRoads,msBuildings&disable_features=boundaries

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

_No response_

### LINKED ISSUE #1380: Wayback imagery: Add spinner
### Description

Video: 

https://github.com/facebook/Rapid/assets/111561/4fb1bb75-78c4-4b0f-afce-01e248f2f5b4

### LINKED ISSUE #1381: Wayback imagery: Cannot select them anymore / dropdown disappeared
### Description

Video: 

https://github.com/facebook/Rapid/assets/111561/83b15b55-c952-4d1f-84bc-306f1eb0c42d

The video shows that the dropdown next to the wayback imagery is gone and I cannot get it to show up again.
I am also not sure if the images are used, I clicked around a bunch to see but not sure.

1. I did not do a lot in this session, I just changed the years of imagery to see the lake in different years and the mapped the lake smaller.
2. I then opened the commit UI and wrote a message and saw that only one image way referenced in the changeset tags.
3. I wanted to see if the wayback images would show up if selected, so I closed the commit panel and this is when I noticed the bug / took the video
    - Update: It is indeed, it would say … `imagery_used=World Imagery (Wayback 2022-05-18) + source=aerial imagery`

Not sure if the commit UI thing is related, though.

### Screenshots

_No response_

### Version

canary

### What browser are you seeing the problem on? What version are you running?

_No response_

### The OS you're using

_No response_

### Steps to reproduce

-

### The browser URL at the time you encountered the bug

https://rapideditor.org/canary#map=17.85/52.70693/13.87971&background=Brandenburg-DOP20c&datasets=fbRoads,msBuildings&disable_features=boundaries

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

_No response_

### LINKED ISSUE #1382: Restore missing favorite buttons on imagery list
Previously we had these stars so that users could mark their favorite imagery:
Screenshot 2024-04-22 at 10 32 24 AM

At some point they went missing.. (They are actually still there, just invisible):

missing_favorites

### PR DESCRIPTION
**Pull request by bhousel**
closes #1377
closes #1379
closes #1380
closes #1381 
closes #1382 
cc @tordans  

This moves Esri Wayback to its own source in the main background list, and fixes a bunch of other stuff.
- Having it as its own source means that there is no confusion about the relationship between the radio button and the previous checkbox
- It also allows the user to lock in a date and switch between the wayback source and another source with the <kbd>⌘B</kbd> shortcut
- This fixes a bunch of tricky interactions with the urlhash too.  We fetch all the wayback sources at init time - this means that if a urlhash contains a param like `background=EsriWayback_2024-01-01`, it will be available when Rapid starts up and will just work.  If the user manually manipulates with the urlhash, the code will pick the closest date that makes sense.
- Also better defers the work of fetching the available "local release dates"  (these are the dates that the imagery appears changed in the current map view).  Because this is an expensive call, we now do it during idle time and cache the results per z14 tile, so it won't refresh unless the user moves the map a bunch, and there won't be a need for a spinner when the user tries to use the dropdown.  
- The dropdown will always show the current date, the oldest date, and the newest date.   From what I can tell, the newest date seems to match "Esri World Imagery" and the oldest date seems to match "Esri World Imagery Clarity". 

Screenshot 2024-04-25 at 1 41 24 PM
Screenshot 2024-04-25 at 1 41 10 PM

### CODE REVIEW

**Comment by tordans** [comment]
This looks like great improvements!

---

FYI I used the feature recently to check out walter level changes and wrote about it in https://en.osm.town/@tordans/112301870063364573

---

Side note: I still don't understand if/when a branch preview is created :-).

**Comment by bhousel** [comment]
> Side note: I still don't understand if/when a branch preview is created :-).

We aren't totally sure either 😆 
It seems like the conditions are:
- PR made by a project team member
- and the PR will merge cleanly to main without conflicts

**Comment by bhousel** [comment]
Thanks @tordans !  
BTW I did change the source id for this layer to `EsriWayback` so it won't conflict with the other `EsriWorldImagery` source.   I think this might be ok, but it will mean your URL that you shared on Mastodon would stop working after this merges.

**Comment by bhousel** [comment]
I fixed the metadata display too, the [wayback-core](https://github.com/vannizhang/wayback-core) library has a helpful function that made this really easy!  🎉 

Interestingly, with the metadata now available, it becomes obvious that the release dates don't match the vintage dates.  This makes sense when you think about it - there will be a lag between when the imagery is captured and released - but I wonder whether it will be confusing to users.  Users seeing a date will probably assume it's the "captured on" date.

Screenshot 2024-04-26 at 11 27 01 AM

**Pull request merged**
