### PR TITLE
Add an example of working with Rapid in an `iframe`

### LINKED ISSUE #1404: Test Rapid embed in iframe
We have a handful of situations where partners are starting to embed Rapid in an `<iframe>` within a containing site and running into various issues.  

We haven't specifically tested this situation, but it will be necessary to make this work well for wider Rapid adoption, so I'm going to make a dedicated test page like `/dist/embed.html`, both to serve as an example implementation and to test that Rapid works seamlessly in this configuration.

### PR DESCRIPTION
**Pull request by bhousel**
closes #1404

We should test this a bit and make sure that things like login/logout work ok.

Doing stuff with `window` in the iframe may cause surprises.
For example, popups to do authentication maybe should do `window.top` instead of `window` if it doesn't already.
https://developer.mozilla.org/en-US/docs/Web/API/Window/top
https://stackoverflow.com/a/2161402/7620

### CODE REVIEW

**Comment by bhousel** [comment]
Cool the deployment did work.. 🚀 
The examples are in a subfolder under `dist/` so they get deployed too.

The iframe example can be tested with this url:
https://rapideditor.org/rapid/pull-request-1439/examples/iframe/parent.html

**Comment by tordans** [comment]
Wow, that sync between sidebar, editor and URL works perfect. 

(Tested sidebar to editor, editor to url, private browsing login until save-screen.)

**Comment by bhousel** [comment]
I noticed that OAuth to osm is failing because we're calculating a `redirect_uri` like 
`"http://127.0.0.1:8080/dist/examples/iframe/child.htmlland.html"`

It's just appending `land.html` to the end of `window.location.origin` which will not work if there is a filename at the end of the pathname.

This `redirect_uri` value can be overridden in our OAuth options, but I'm going to push a change that helps it pick a better default value.

**Comment by bhousel** [comment]
Seems good!  I've checked a bunch of things that involve `window` and they are all working:
- `window.URL.createObjectURL`, used to download an OsmChange file
- `window.open`, for situations like like the login/logout windows (they open in '_blank' anyway)
- `window.confirm`, for the message when you have edits and attempt to switch to the dev server
- drag and drop of gpx files , (the handlers are attached to container in the child)
- 'navigator.geolocate' for "show my location"

**Comment by bhousel** [comment]
Cool this has been merged to main, and I did some setup adjustments so that the canary folder all gets synced now.

The examples are available on urls :
link to the examples page:  https://rapideditor.org/canary/examples/index.html
link to the iframe example:  https://rapideditor.org/canary/examples/iframe/parent.html

**Comment by tordans** [comment]
@bhousel I there is a off by one error in the demo

1. open https://rapideditor.org/rapid/pull-request-1439/examples/iframe/parent.html#map=19.00/39.32079/-74.51139/53.0&background=OpenAerialMapMosaic&datasets=fbRoads,msBuildings&disable_features=boundaries
2. change layer to mapbox 
  - …but URL is still https://rapideditor.org/rapid/pull-request-1439/examples/iframe/parent.html#map=19.00/39.32079/-74.51139/53.0&background=OpenAerialMapMosaic&datasets=fbRoads,msBuildings&disable_features=boundaries
  - …but sidebar shows `Imagery:	Mapbox Satellit `
3. toggle osm data (or any other state change) and the URL of the background param updates to mapbox

**Comment by bhousel** [comment]
Thanks @tordans  -  It's not actually an [off-by-one](https://en.wikipedia.org/wiki/Off-by-one_error), but I can explain what your'e seeing. This of makes sense to me, because of the asyncness of things...  Here's what happens:

1. user changes background imagery
2. `ImagerySystem.baseLayerSource` will deal with the change.. It calls `updateImagery()` to actually handle the change and update the (child window) URL hash.  
3. At this point `UrlHashSystem.setParam()` only queues the change, it doesn't do it.  This is because hash changes can happen a lot (imagine dragging the map) so the hash doesn't actually update for like a half second.  
4. Then `ImagerySystem.baseLayerSource() emits an `imagerychange` event.
5. `MapSystem` receives that event and calls `immediateRedraw` - This actually is also async!  "immediate" means, trigger a redraw on the next animation frame.  The user just did something and expects to see the map change.
6. It takes 2 animation frames to do everything, but when that redraw does happen (some milliseconds later), `MapSystem` will emit `draw` event.  The parent iframe will notice this and update the sidebar to say "Mapbox".  The child UrlHash hasn't updated yet!
7. Around a half second later, the child iframe will update.. I don't think there's a good event for the parent to listen to that would catch this, but I can add one to `UrlHashSystem`.
8. Some time later you move the mouse or "toggle OSM data" or do something that would trigger another 'draw' and then the parent iframe picks up the change.

I thought that by having the parent iframe listening to `MapSystem` `draw` , this is called frequently enough that the state will eventually make it's way up to the parent.  But I could add an event to `UrlHashSystem` so that listeners know when a hash change has occurred for any reason.

**Pull request merged**
