### PR TITLE
Holiday Themed Cursors 

### PR DESCRIPTION
**Pull request by tannerwuster**
## Description 
Christmas themed cursors are here and yes they are ugly of course 

- Gingerbread cookie 
- Christmas tree 
- Santa claus 
- Candy cane

https://github.com/facebook/Rapid/assets/49957271/0ba96b3b-9a17-4b29-add4-1c7d48bb3524

### CODE REVIEW

**Comment by Bonkles** [comment]
Yessssss

**Comment by Bonkles** [comment]
Ah, looks like you just need to rebase given that I updated a couple things!

**Comment by voscarmv** [comment]
Hey @tannerwuster how does one go about adding this one to the ugly Christmas cursors? https://pngimg.com/uploads/santa_sleigh/santa_sleigh_PNG5.png

**Comment by tannerwuster** [comment]
> Hey @tannerwuster how does one go about adding this one to the ugly Christmas cursors? https://pngimg.com/uploads/santa_sleigh/santa_sleigh_PNG5.png

It has now been added! 😁

**Comment by tannerwuster** [comment]
> Ah, looks like you just need to rebase given that I updated a couple things!

Rebased and should be good to go 🎅🏼

**Comment by voscarmv** [comment]
> > Hey @tannerwuster how does one go about adding this one to the ugly Christmas cursors? https://pngimg.com/uploads/santa_sleigh/santa_sleigh_PNG5.png
> 
> It has now been added! 😁

Thank you @tannerwuster !!

**Comment by Bonkles** [comment]
@tannerwuster Happy 🦃 day! No rush, but it looks like perhaps you didn't push your changes after the rebase- I still see the same conflicting files.

**Pull request merged**
