### PR TITLE
Sidebar fixes

### PR DESCRIPTION
**Pull request by bhousel**
This fixes a few known issues with the sidebar
#1468 
#1479 

While in the sidebar code I did a _bunch_ of other cleanups:
- Added a proper resizer handle
- Fix how resizing works (see below)
- Fix a handful of RTL (right to left) issues.  
- Flexbox everything in this part of the UI : container, sidebar, main content, inspector and other sidebar content 
   (this allows us to much easier keep track of how wide the user actually wants the sidebar to be)
- Update some of this code to class components (I'm finding this style of code a lot easier to reason about as to when they are created, when they render, etc than our old idiomatic D3 UI code)

OLD:
old resize

NEW:
new resize

### CODE REVIEW

**Comment by bhousel** [comment]
BTW I don't really like this "inspect" button.  If users can click on the resizer to toggle it, we don't need an extra button for this.  I am also imagining a UI that works better for mobile or vertical screen orientations, where the drawer slides in from the bottom, not the side.  Now that the whole thing is flexboxed, it doesn't need to be on the side necessarily.

Does anyone have an opinion on whether the button should stay or go?

Screenshot 2024-07-31 at 2 46 01 PM


toggle

**Comment by Bonkles** [comment]
I, too, despise the inspect button. 

My thoughts: 
- Remove it for desktop. You've already replicated its toggle functionality when the user clicks-and-releases the innermost edge of the sidebar, so I don't see the value it provides. 
  - Is there some way we could make the sidebar expand shortcut more discoverable without having to hunt for it in the keyboard shortcuts dialog? 

-For mobile, we should probably include *something* for the user to click on to expand/contract, as  edge-of-screen taps/gestures are really hard to do / already overloaded on a lot of phones/tablets.

**Comment by bhousel** [comment]
> -For mobile, we should probably include _something_ for the user to click on to expand/contract, as edge-of-screen taps/gestures are really hard to do / already overloaded on a lot of phones/tablets.

Now that we're using flexbox for layout, mobile could look like this.  A thing I made in about 3 minutes just playing with a few CSS properties in the Chrome dev tools by switching `flex-flow` from `row` to `column` and a few other tweaks.

Screenshot 2024-07-31 at 4 43 08 PM

**Comment by bhousel** [comment]
It actually works pretty well 😎 
It needs work but it's better than having it stuck on the side.

rapid mobile drawer

**Comment by Bonkles** [comment]
I would say yeah go with that- but pick whichever axis is longer to do the accordion thing (say, if the user has their phone on its side, we should absolutely change the flex flow and collapse left-right)

**Review by Bonkles — APPROVED** [review]
solid, proper, grade A.

**Comment by bhousel** [comment]
> * Remove it for desktop. You've already replicated its toggle functionality when the user clicks-and-releases the innermost edge of the sidebar, so I don't see the value that the inspect button provides.
>   
>   * Is there some way we could make the sidebar expand shortcut more discoverable without having to hunt for it in the keyboard shortcuts dialog?

Cool, yeah I agree totally..

* I removed the toggle button and moved the tooltip to the sidebar resizer to make the shortcut discoverable.
* I made the tooltip open on the sidebar side (so it would avoid popping over the map while the user is doing map stuff).
* I also made it hide when the user starts resizing.

resizer tooltip

**Pull request merged**
