### PR TITLE
flash the base layer name when changed using keys

### PR DESCRIPTION
**Pull request by KhalfounMehdi**
Flash the base layer name when changed using keys
issue : #837 
### New behaviour : 

https://user-images.githubusercontent.com/67844770/226511859-49bba396-8bb3-460f-b5d6-eea6fafa9da1.mp4

### CODE REVIEW

**Comment by bhousel** [comment]
Yeah I don't even think we should flash anything - we can just find room for the thing the user wants to see.

I get that there are situations where it is hard to see what imagery layer the user has switched to, but we can fix that problem without flashing.

Maybe just add a second row in the footer for the imagery name and various attributions.?

Screenshot 2023-03-21 at 9 19 18 AM

**Comment by Bonkles** [comment]
I think this idea is even better!

**Comment by mvexel** [comment]
I didn't clarify very well what I meant by 'flashing' when I filed the original ticket.

I think what @bhousel proposes, to just clean up the imagery layer source text, making it uniform and readable on a variety of background colors, makes sense.

**Comment by bhousel** [comment]
Going to close this draft PR since we don't actually want the "flashing" .

**Pull request closed without merging**
