### PR TITLE
Checkboxes in indeterminate state are now grey

### LINKED ISSUE #1629: Checkboxes in indeterminate state should style more like unchecked than checked
I feel like these look too much like "checked":

Screenshot 2024-11-28 at 10 35 14 AM

We should be able to target these with the `:indeterminate` pseudo class.
https://developer.mozilla.org/en-US/docs/Web/CSS/:indeterminate

### PR DESCRIPTION
**Pull request by tannerwuster**
Screenshot 2024-12-04 at 13 29 31

closes #1629

### CODE REVIEW

**Comment by bhousel** [comment]
Hey that looks great!
Does it still work if you get rid of the `.form-field-input-check >` part?  
Maybe we could just move this rule towards the beginning of the file with the other styling rules for checkboxes anywhere in Rapid.

**Comment by tannerwuster** [comment]
> Hey that looks great! Does it still work if you get rid of the `.form-field-input-check >` part? Maybe we could just move this rule towards the beginning of the file with the other styling rules for checkboxes anywhere in Rapid.

I just made that change and it worked!

**Comment by bhousel** [comment]
Awesome! haha love the branch name too ♟️

**Comment by bhousel** [comment]
Oh wait, this changed all the checkboxes - it needs to be its own rule that targets only the indeterminate state.
@tannerwuster can add your rule after the checkbox rule instead of joining it with a comma `,`?

Screenshot 2024-12-09 at 12 49 36 PM
Screenshot 2024-12-09 at 12 52 41 PM

**Pull request merged**
